package com.oktaysadoglu.memofication.fragments.game_fragment.pojo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "WORD".
 */
public class Word {
    @SerializedName("id")
    private Long id;
    @SerializedName("name")
    private String word;
    @SerializedName("mean")
    private String mean;
    @SerializedName("type")
    private String type;

    public Word() {
    }

    public Word(Long id) {
        this.id = id;
    }

    public Word(Long id, String word, String mean, String type) {
        this.id = id;
        this.word = word;
        this.mean = mean;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWord() {
        return word;
    }

    public void setWord(String word) {
        this.word = word;
    }

    public String getMean() {
        return mean;
    }

    public void setMean(String mean) {
        this.mean = mean;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getIntId(){

        return (int) (long) id;

    }

    @Override
    public String toString() {
        return "Word{" +
                "id=" + id +
                ", word='" + word + '\'' +
                ", mean='" + mean + '\'' +
                ", type='" + type + '\'' +
                '}';
    }
}
